project:
  type: website
  output-dir: docs

website:
  title: "Fintech 533: Strategy Lab"
  navbar:
    background: primary
    type: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: breakout_strategy.ipynb
        text: Breakout Strategy

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true